# Generated by Django 3.2.23 on 2023-11-19 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='Default Shop', max_length=50, null=True, verbose_name='Shop Name')),
                ('shop_bio', models.CharField(blank=True, default='Default Shop Bio', max_length=500, null=True, verbose_name='Shop Bio')),
                ('shop_logo', models.CharField(blank=True, default='Default Shop Logo', max_length=50, null=True, verbose_name='Shop Logo')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shop Owner')),
            ],
        ),
    ]
