# Generated by Django 3.2.23 on 2023-11-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopbuzz', '0002_alter_shop_shop_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(blank=True, default='Default Shop', max_length=50, null=True, verbose_name='Product Name')),
                ('prod_bio', models.CharField(blank=True, default='Default Shop Bio', max_length=500, null=True, verbose_name='Product Bio')),
                ('prod_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopbuzz.shop', verbose_name='Shop Name')),
            ],
        ),
    ]
